### ISSUE TITLE
Journal 10/09/2024

### ISSUE THREAD

**Issue by aliceafanasieva** [aliceafanasieva/i-love-web#12]
<h2> Wat wil ik vandaag doen? </h2>

- [ ]  #22 in repository i-love-web om makkelijk te werken aan verschillende taken en projecten
- [ ]  #21 
- [ ] #13 

<h2> Wat is mij gelukt? </h2>

- [ ] #22 - Ik heb veel tijd besteed aan het uitzoeken hoe ik efficient moet werken met issues etc. maar dit is mij uiteindelijk gelukt.
- [ ] #21 - Ik moest ook nog even zitten en kijken hoe branches werken, maar dit is mij ook gelukt.

<h2>Waar moet ik nog aan werken?</h2>

- [ ] #13 - Ik ga morgen werken aan dit issue. 
- [ ] #14 
- [ ] #23
